"""
Quiz Model - Daily Quizzes
===========================
Pydantic models for the quizzes collection.
Represents AI-generated quizzes based on chat history for gamification.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, List, Union
from datetime import datetime, date
from bson import ObjectId


class PyObjectId(str):
    """Custom ObjectId type for Pydantic v2 models."""
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema
        
        def validate(value, _info=None):
            if isinstance(value, ObjectId):
                return str(value)
            if isinstance(value, str):
                if ObjectId.is_valid(value):
                    return value
                raise ValueError("Invalid ObjectId")
            raise ValueError("Invalid ObjectId type")
        
        return core_schema.with_info_plain_validator_function(
            validate,
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda x: str(x)
            )
        )


class QuizQuestion(BaseModel):
    """Individual quiz question with multiple choice options."""
    question_id: str  # Unique ID for the question (e.g., "q1", "q2")
    question_text: str = Field(..., min_length=5, max_length=500)
    options: List[str] = Field(..., min_length=2, max_length=4)
    correct_answer: str = Field(..., description="Must be one of the options")
    user_answer: Optional[str] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "question_id": "q1",
                "question_text": "What gas do plants release during photosynthesis?",
                "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
                "correct_answer": "Oxygen",
                "user_answer": None
            }
        }


class QuizCreate(BaseModel):
    """Schema for creating a quiz (generated by AI)."""
    profile_id: str
    topic: str = Field(..., min_length=3, max_length=100)
    source_conversation_ids: List[str] = Field(default_factory=list, description="Conversations used to generate quiz")
    questions: List[QuizQuestion] = Field(..., min_length=5, max_length=10)
    difficulty: str = Field(default="medium", pattern="^(easy|medium|hard)$")
    quiz_date: date = Field(default_factory=date.today, description="Date for which quiz was generated")
    
    class Config:
        json_schema_extra = {
            "example": {
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis and Plant Biology",
                "source_conversation_ids": ["507f1f77bcf86cd799439013"],
                "questions": [
                    {
                        "question_id": "q1",
                        "question_text": "What gas do plants release?",
                        "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
                        "correct_answer": "Oxygen",
                        "user_answer": None
                    }
                ],
                "difficulty": "medium",
                "quiz_date": "2024-01-20"
            }
        }


class QuizInDB(BaseModel):
    """Quiz model as stored in MongoDB."""
    id: Optional[PyObjectId] = Field(default=None, alias="_id")
    profile_id: PyObjectId
    topic: str
    source_conversation_ids: List[PyObjectId] = Field(default_factory=list)
    questions: List[QuizQuestion]
    difficulty: str = Field(default="medium")
    quiz_date: date = Field(default_factory=date.today)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = Field(default="pending", pattern="^(pending|completed)$")
    score: Optional[int] = Field(default=None, ge=0, le=100)
    completed_at: Optional[datetime] = None
    xp_earned: Optional[int] = Field(default=None, ge=0)
    
    @field_validator('quiz_date', mode='before')
    @classmethod
    def convert_datetime_to_date(cls, v):
        """Convert datetime from MongoDB to date."""
        if isinstance(v, datetime):
            return v.date()
        return v
    
    class Config:
        populate_by_name = True
        from_attributes = True
        json_encoders = {
            ObjectId: str,
            datetime: lambda v: v.isoformat(),
            date: lambda v: v.isoformat()
        }
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439014",
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis and Plant Biology",
                "source_conversation_ids": ["507f1f77bcf86cd799439013"],
                "questions": [],
                "difficulty": "medium",
                "quiz_date": "2024-01-20",
                "created_at": "2024-01-20T10:00:00",
                "status": "pending",
                "score": None,
                "completed_at": None,
                "xp_earned": None
            }
        }


class QuizResponse(BaseModel):
    """Quiz response model (without answers for active quizzes)."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    created_at: datetime
    status: str
    score: Optional[int] = None
    completed_at: Optional[datetime] = None
    xp_earned: Optional[int] = None
    total_questions: int
    
    class Config:
        populate_by_name = True
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439014",
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis",
                "difficulty": "medium",
                "quiz_date": "2024-01-20",
                "created_at": "2024-01-20T10:00:00",
                "status": "pending",
                "score": None,
                "completed_at": None,
                "xp_earned": None,
                "total_questions": 5
            }
        }


class QuizQuestionsResponse(BaseModel):
    """Quiz with questions (for taking quiz - without correct answers)."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    questions: List[dict]  # Questions without correct_answer field
    total_questions: int
    
    class Config:
        populate_by_name = True


class QuizSubmission(BaseModel):
    """Schema for submitting quiz answers."""
    answers: dict = Field(..., description="Dictionary mapping question_id to user's selected answer")
    
    class Config:
        json_schema_extra = {
            "example": {
                "answers": {
                    "q1": "Oxygen",
                    "q2": "Energy ke liye",
                    "q3": "Chlorophyll"
                }
            }
        }


class QuizSubmissionResponse(BaseModel):
    """Response after submitting quiz with results."""
    quiz_id: str
    score: int = Field(..., ge=0, le=100)
    correct_count: int
    total_questions: int
    xp_earned: int
    current_xp: int
    streak_days: int
    streak_maintained: bool
    feedback: List[dict] = Field(..., description="Per-question feedback")
    
    class Config:
        json_schema_extra = {
            "example": {
                "quiz_id": "507f1f77bcf86cd799439014",
                "score": 80,
                "correct_count": 4,
                "total_questions": 5,
                "xp_earned": 40,
                "current_xp": 1540,
                "streak_days": 4,
                "streak_maintained": True,
                "feedback": [
                    {
                        "question_id": "q1",
                        "correct": True,
                        "user_answer": "Oxygen",
                        "correct_answer": "Oxygen"
                    }
                ]
            }
        }
